CI add cereal dependency
mlpack/examples pull request #133
Opened 2020-11-02 22:44 UTC by zoq

mlpack serialization builds on cereal, which is currently not part of the CI build pipeline.

2020-11-02 23:47 UTC, rcurtin approved these changes
Nice catch!  Looks good to me. :+1:

2020-11-02 23:48 UTC, birm requested changes
Noted error "/usr/include/mlpack/prereqs.hpp:86:38: fatal error: cereal/archives/binary.hpp: No such file or directory"

2020-11-02 23:48 UTC, rcurtin commented on .travis.yml
> +  - tar -xvzpf v1.3.0.tar.gz
Oops, I approved too early.  I had just assumed that it worked. :smile:  If you use CMake to install cereal into /usr (so `CMAKE_INSTALL_PREFIX=/usr` when you configure cereal, then it shouldn't be necessary to specify `CEREAL_INCLUDE_DIR` when configuring mlpack and the examples should build and run okay. :+1:

2020-11-03 14:26 UTC, birm approved these changes
It looks like $target_name isn't set for the cereal directory, probably because it's not actually a test. Probably a good idea to fix that, but it looks like the examples are testing ok.

2020-11-04 22:41 UTC, rcurtin commented
Everything looks good to me now; I think it's ready for merge. :+1:

2020-11-06 17:27 UTC, merged