Added Linear Regression for predicting salary
mlpack/examples pull request #149
Opened 2021-04-12 09:28 UTC by Davidportlouis

- [x]  C++ implementation
- [x]  Python implementation
- [ ]  Julia implementation
- [x] Visualization and graphs
- [x]  Inline Comments
- [ ]   Dataset source

2021-04-16 02:16 UTC, zoq commented
@Davidportlouis nice, do you have a link to the dataset?

2021-04-17 06:47 UTC, Davidportlouis commented
> 
> 
> @Davidportlouis nice, do you have a link to the dataset?
Link to Dataset
[Salary data - Simple linear regression](https://www.kaggle.com/karthickveerakumar/salary-data-simple-linear-regression)

2021-04-22 21:58 UTC, rcurtin reviewed
Hey @Davidportlouis, thanks for adding this!  I also added some ReviewNB comments. :+1:

2021-04-22 21:58 UTC, rcurtin commented on salary_prediction_with_linear_regression/salary_prediction_linear_regression.cc
> +#include<cmath>
```suggestion
#include <mlpack/core.hpp>
#include <mlpack/core/data/split_data.hpp>
#include <mlpack/methods/linear_regression/linear_regression.hpp>
#include <cmath>
```
Just a simple style sugestion---I think maybe it would be worth going through the file for style changes.

2021-04-22 21:58 UTC, rcurtin commented on salary_prediction_with_linear_regression/salary_prediction_linear_regression.cc
> +namespace plt = matplotlibcpp;
If you're doing visualization here, does it make more sense to convert this into a C++ notebook like some of the other ones in this repository?  Most of our 'standalone C++ program' examples are meant to load data, train a model, compute predictions, and then save them to file.

2021-04-22 21:58 UTC, rcurtin commented on salary_prediction_with_linear_regression/salary-prediction-linear-regression-py.ipynb
> +{
<p>We might not need this cell---we could just replace it with a Markdown cell describing what the goals of the example are.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/mlpack/examples/pull/149/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='0'/>

2021-04-22 21:58 UTC, rcurtin commented on salary_prediction_with_linear_regression/salary-prediction-linear-regression-py.ipynb
> +{
<p>You could just inline this as a comment; I'm not sure if it's necessary.  Personally I think if we have a Markdown cell / header, we should have a little explanation as to what we are trying to do.  Many people coming to these examples may be new to data science in general, so it can be a good idea to explain a little of why we are doing something. :+1:</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/mlpack/examples/pull/149/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='1'/>

2021-04-22 21:58 UTC, rcurtin commented on salary_prediction_with_linear_regression/salary-prediction-linear-regression-py.ipynb
> +{
<p>For instance, some of the other notebooks have some text with each of the sections like this to describe what they are doing and why.  Maybe it would be a good idea to take a look at those for some ideas?</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/mlpack/examples/pull/149/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='5'/>

2021-04-22 21:58 UTC, rcurtin commented on salary_prediction_with_linear_regression/salary-prediction-linear-regression-py.ipynb
> +{
<p>Hmm, I'm not sure if a heatmap is particularly useful here unless we have a lot of parameters.  The scatter plot you did below is nice though.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/mlpack/examples/pull/149/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='11'/>

2021-04-22 21:58 UTC, rcurtin commented on salary_prediction_with_linear_regression/salary-prediction-linear-regression-py.ipynb
> +{
<p>Is a colormap the right thing to do here?  Or should we just use years for the x axis?</p><p> </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/mlpack/examples/pull/149/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='12'/>

2021-04-22 21:58 UTC, rcurtin commented on salary_prediction_with_linear_regression/salary-prediction-linear-regression-py.ipynb
> +{
<p>It's up to you, but sometimes it can be nice to run these with <code>verbose=True</code>  so that it gives a little bit of output.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/mlpack/examples/pull/149/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='18'/>

2021-04-22 21:58 UTC, rcurtin commented on salary_prediction_with_linear_regression/salary-prediction-linear-regression-py.ipynb
> +{
<p>Nice!  I like overlaying the model line onto the original data.  It gives a nice image of how good the fit is.  Do you think you could add a legend that points out what the line is?  (Or some text in a Markdown block describing the figure or something.)</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/mlpack/examples/pull/149/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='24'/>

2021-04-23 03:34 UTC, Davidportlouis commented on salary_prediction_with_linear_regression/salary_prediction_linear_regression.cc
> +namespace plt = matplotlibcpp;
I have some issues with visualization and even running mlpack (I tried to cout an armadillo matrix and my kernel dies "repeatedly") using xeus-cling in jupyter on my local machine, I'm currently planning to do a clean install of miniconda and xeus-cling, so I'll look into converting it to C++ notebook

2021-04-26 05:10 UTC, Davidportlouis commented on salary_prediction_with_linear_regression/salary_prediction_linear_regression.cc
> +namespace plt = matplotlibcpp;
> I have some issues with visualization and even running mlpack (I tried to cout an armadillo matrix and my kernel dies "repeatedly") using xeus-cling in jupyter on my local machine, I'm currently planning to do a clean install of miniconda and xeus-cling, so I'll look into converting it to C++ notebook

I solved this problem, I'll convert the standalone cpp file into a ipynb ASAP

2021-04-29 02:53 UTC, zoq commented on salary_prediction_with_linear_regression/salary-prediction-linear-regression-py.ipynb
> +{
<p>Agreed, I would remove the plot.</p>

2021-04-29 02:54 UTC, zoq commented on salary_prediction_with_linear_regression/salary-prediction-linear-regression-py.ipynb
> +{
<p>Agreed, right now if I just look at the plot I don't know what this shows, also looks like a comment is missing.</p>

2021-04-29 03:02 UTC, zoq commented on salary_prediction_with_linear_regression/salary-prediction-linear-regression-py.ipynb
> +{
<p>Let's use the same comment style as we use for mlpack, checkout https://github.com/mlpack/mlpack/wiki/DesignGuidelines#comments for more details, In this case you are missing a stop <code>.</code></p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/mlpack/examples/pull/149/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='6'/>

2021-04-29 03:02 UTC, zoq commented on salary_prediction_with_linear_regression/salary-prediction-linear-regression-py.ipynb
> +{
<p>The comment should start with a capital letter and and with a stop.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/mlpack/examples/pull/149/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='7'/>

2021-04-29 03:02 UTC, zoq commented on salary_prediction_with_linear_regression/salary-prediction-linear-regression-py.ipynb
> +{
<p>Missing stop at the end of the line.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/mlpack/examples/pull/149/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='15'/>

2021-04-29 03:02 UTC, zoq commented on salary_prediction_with_linear_regression/salary-prediction-linear-regression-py.ipynb
> +{
<p>Personally I would remove the extra step here, for one I think <code>output["training"]</code>is already pretty readable and the other aspect is that in most cases we use camel casing for all names.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/mlpack/examples/pull/149/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='16'/>

2021-04-29 03:02 UTC, zoq commented on salary_prediction_with_linear_regression/salary-prediction-linear-regression-py.ipynb
> +{
<p>Do you mind to put a space behind <code>,</code> there are some other places that uses a different style as well.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/mlpack/examples/pull/149/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='22'/>

2021-04-29 03:02 UTC, zoq commented on salary_prediction_with_linear_regression/salary-prediction-linear-regression-py.ipynb
> +{
<p>Can you add a markdown cell and say some words about the metrics you printed here, to help the user to understand if the results are good or not.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/mlpack/examples/pull/149/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='26'/>

2021-04-29 03:52 UTC, Davidportlouis commented on salary_prediction_with_linear_regression/salary_prediction_linear_regression.cc
> +namespace plt = matplotlibcpp;
Completed the interactive notebook for C++, thanks for the suggestions they were very helpful.
Also I encountered a problem while loading the saved plot image using xwidget (the xeus-cling kernel dies), any ideas on how to fix it.

2021-04-29 03:52 UTC, Davidportlouis commented on salary_prediction_with_linear_regression/salary-prediction-linear-regression-py.ipynb
> +{
Replaced it with inline comment

2021-04-29 03:54 UTC, Davidportlouis commented on salary_prediction_with_linear_regression/salary-prediction-linear-regression-py.ipynb
> +{
Removed the heatmap, looking back it kind of made no sense. Thanks for the suggestion.

2021-04-29 03:55 UTC, Davidportlouis commented on salary_prediction_with_linear_regression/salary-prediction-linear-regression-py.ipynb
> +{
Removed the colormap, colorbar and added axes labels and title for the plot

2021-04-29 03:55 UTC, Davidportlouis commented on salary_prediction_with_linear_regression/salary-prediction-linear-regression-py.ipynb
> +{
Added legend in the plot indicating linear model

2021-04-29 03:56 UTC, Davidportlouis commented on salary_prediction_with_linear_regression/salary-prediction-linear-regression-py.ipynb
> +{
Sure, I'll use the same comment style. Thank you for the suggestion

2021-04-29 03:57 UTC, Davidportlouis commented on salary_prediction_with_linear_regression/salary-prediction-linear-regression-py.ipynb
> +{
Added brief explanation about each evaluation metric in the preceding markdown

2021-04-30 01:48 UTC, zoq commented on salary_prediction_with_linear_regression/salary-prediction-linear-regression-py.ipynb
> +{
<p>Nice!</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/mlpack/examples/pull/149/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='22'/>

2021-04-30 01:51 UTC, zoq reviewed
Are you planning to add the Julia as part of the PR, or do you think we should open a separate PR?

2021-04-30 01:55 UTC, Davidportlouis commented
> Are you planning to add the Julia as part of the PR, or do you think we should open a separate PR?

I'll open separate PR.

2021-04-30 02:05 UTC, zoq commented
Okay, great, let's merge https://github.com/mlpack/examples/pull/151 first, because this will change some things on the cpp notebook.

2021-05-11 22:15 UTC, rcurtin commented on salary_prediction_with_linear_regression/salary-prediction-linear-regression-py.ipynb
> +{
<p>Agreed, this is a nice description!  It would be great if you could add it to the C++ notebook too.  But, one thing worth adding is that many readers may not know <em>why</em> we have this section here.  So, for instance, maybe you could add a paragraph like this:</p><p> </p><p>"Now that we have seen a quick visualization of our model, it is useful to get a quantitative measurement of how good the model is.  This will allow us to compare the quality of this model with other models, and get a feel for how 'good' the fit is.  There are tons of choices of evaluation metrics; here, we focus on three popular choices:"</p><p> </p><p>(and then the description that you already have)</p>

2021-05-11 22:17 UTC, rcurtin commented on salary_prediction_with_linear_regression/salary-prediction-linear-regression-cpp.ipynb
> +{
<p>I think for both the C++ and Python examples, it would be really nice to add a header and then a paragraph or two describing what happens in the example.  This will allow a reader who opens the file to quickly decide whether or not it's worthwhile to actually go through the example.  I'm thinking something like a quick summary or an abstract, but if you have a better idea that works too. :)</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/mlpack/examples/pull/149/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='0'/>

2021-05-11 22:17 UTC, rcurtin commented on salary_prediction_with_linear_regression/salary-prediction-linear-regression-cpp.ipynb
> +{
<p>Maybe it makes sense to combine the three cells above into one, because it's all "environment setup"?</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/mlpack/examples/pull/149/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='2'/>

2021-05-11 22:17 UTC, rcurtin commented on salary_prediction_with_linear_regression/salary-prediction-linear-regression-cpp.ipynb
> +{
<p>Why convert to size_t here, then back to rowvec later?  Couldn't you just do <code>arma::rowvec targets = inputs.row(inputs.n_rows - 1);</code>  here?</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/mlpack/examples/pull/149/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='7'/>

2021-05-11 22:17 UTC, rcurtin commented on salary_prediction_with_linear_regression/salary-prediction-linear-regression-cpp.ipynb
> +{
<p>Overall the example looks good to me.  Keep in mind though that many people reading this example will not be familiar with mlpack and may not be very knowledgeable about data science in general.  So, it could be really useful to add some Markdown cells to the beginning of each "section" describing what that section does (e.g., training, testing, loading data, computing metrics) and more importantly <em>why</em> that's something worth doing.</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/mlpack/examples/pull/149/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='15'/>

2021-05-11 22:17 UTC, rcurtin commented on salary_prediction_with_linear_regression/salary-prediction-linear-regression-py.ipynb
> +{
<p>It could be helpful here, too, to add a bit describing why these are good results to the user (who may not know what to do with the computations or how to interpret them).  Personally, I would say that this is a reasonably good fit, because our MAE is ~5k, which is relatively small compared to the average salary (something like 80k).</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/mlpack/examples/pull/149/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='24'/>

2021-05-11 22:20 UTC, rcurtin commented
Hey @Davidportlouis, nice improvements!  Thanks for addressing the comments that have been left.  I am not sure how feasible it is, but maybe it would be nice to make the C++ and Python notebooks as similar as possible?  So, e.g., the visualizations and explorations you are doing in Python, maybe we could do the exact same type of things in C++?

The other main comment I have is that it could be really nice if the notebooks told a "story" that the reader could go through.  The code samples are really nice, but I think they are much more usable to people who are new to mlpack or data science in general if we can describe *why* we are doing what we're doing, and how each step is a larger part of the data science process.  To this end, it could be helpful to lay out the objective of the data science task at the beginning of the notebook (in this case, it is to predict someone's salary), and then add some text describing how each section of the notebook gets us closer to completing those objectives. :+1:

2021-05-11 23:29 UTC, zoq commented on salary_prediction_with_linear_regression/salary-prediction-linear-regression-cpp.ipynb
> +    "#include <mlpack/core.hpp>\n",
Some of the includes changed, to be specific you should include `#include <mlpack/xeus-cling.hpp>` now, you can take a look at https://github.com/mlpack/examples/blob/master/student_admission_regression_with_logistic_regression/student-admission-logistic-regression-cpp.ipynb for an example.

2021-05-11 23:29 UTC, zoq commented on salary_prediction_with_linear_regression/salary-prediction-linear-regression-cpp.ipynb
> +{
Agreed, you might want to take a look at https://github.com/mlpack/examples/blob/master/student_admission_regression_with_logistic_regression/student-admission-logistic-regression-cpp.ipynb to see an example, it's not perfect but goes into a good direction.

2021-05-11 23:29 UTC, zoq commented on salary_prediction_with_linear_regression/salary-prediction-linear-regression-cpp.ipynb
> +    "std::cout<<inputs.submat(0, 0, inputs.n_rows-1, 5).t()<<std::endl;"
```suggestion
    "std::cout << std::setw(18) <<\"Years Of Experience\" << std::setw(10) << \"Salary\" << std::endl;\n",
    "std::cout << inputs.submat(0, 0, inputs.n_rows-1, 5).t() << std::endl;"
```

Let's use the same style for notebooks as we do for the mlpack codebase.

2021-05-11 23:29 UTC, zoq commented on salary_prediction_with_linear_regression/salary-prediction-linear-regression-cpp.ipynb
> +    "std::vector<double> y_p = arma::conv_to<std::vector<double>>::from(y_preds);"
Please use camel casing for all names.

2021-05-11 23:29 UTC, zoq commented on salary_prediction_with_linear_regression/salary-prediction-linear-regression-cpp.ipynb
> +    "std::cout<<\"Root Mean Squared Error: \"<<sqrt(arma::mean(arma::pow(y_preds - y_test,2)))<<std::endl;"
```suggestion
    "std::cout << \"Mean Absolute Error: \" << arma::mean(arma::abs(y_preds - y_test)) << std::endl;\n",
    "std::cout << \"Mean Squared Error: \" << arma::mean(arma::pow(y_preds - y_test,2)) << std::endl;\n",
    "std::cout << \"Root Mean Squared Error: \" << sqrt(arma::mean(arma::pow(y_preds - y_test,2))) << std::endl;"
```

Add some spaces between operations.

2021-05-25 05:42 UTC, bkmgit commented
This is a nice example. However, the data set does not have information about whether it is a real dataset or an artificial one, so may not reflect real world use and some of the challenges with predictive models. It may be helpful to add some discussion on this. Might also consider using another dataset, for example age vs. height/weight for which linear regression works well upto about 18 years. See for example https://medium.com/data-science-everywhere/linear-regression-is-simple-81a05da5e0e1 and https://insights.dice.com/2016/02/11/how-much-will-experience-increase-my-salary/

2021-05-28 19:29 UTC, zoq commented
> This is a nice example. However, the data set does not have information about whether it is a real dataset or an artificial one, so may not reflect real world use and some of the challenges with predictive models. It may be helpful to add some discussion on this. Might also consider using another dataset, for example age vs. height/weight for which linear regression works well upto about 18 years. See for example https://medium.com/data-science-everywhere/linear-regression-is-simple-81a05da5e0e1 and https://insights.dice.com/2016/02/11/how-much-will-experience-increase-my-salary/

You are right https://www.kaggle.com/karthickveerakumar/salary-data-simple-linear-regression does not provide any information about the dataset. That said the medium article you linked uses the same dataset.

2021-05-28 20:28 UTC, bkmgit commented
@zoq Yes you are correct. It does start of with a height vs. age dataset though. Some other possible sources of datasets are in https://opendata.stackexchange.com/questions/7793/age-weight-and-height-dataset 

Though these not be used, just a suggestion.

Depending on the audience, something like https://xkcd.com/605/ makes a point about the dangers of regression.

2021-05-28 20:53 UTC, bkmgit commented
Another possible data source is https://ourworldindata.org/human-height

2021-05-28 21:47 UTC, zoq commented
The dataset looks interesting, what about we finish the salary notebook, and then if @Davidportlouis agrees we do another one using the human-height dataset, there is no limit of notebooks we could implement, and the data exploration step for the human-height dataset would be interesting.

2021-05-29 17:32 UTC, Davidportlouis commented
> The dataset looks interesting, what about we finish the salary notebook, and then if @Davidportlouis agrees we do another one using the human-height dataset, there is no limit of notebooks we could implement, and the data exploration step for the human-height dataset would be interesting.

Sure @zoq, I would like to complete the salary prediction notebook, then implement human-height and also some other good datasets.

2021-05-30 03:19 UTC, Davidportlouis commented
![Screenshot from 2021-05-30 08-40-11](https://user-images.githubusercontent.com/18904157/120090805-f053ba80-c122-11eb-9a67-7eab8be1a2c8.png)

Hi, any suggestions on how to fix this issue, every time I execute a cell containing some matplotlibcpp code, the xeus cling kernel dies. 

My Local Env:
OS: Manjaro 21.0.4 
Conda: 4.10.1
Python: 3.7.10
Xeus-cling: 0.9.0.13 (from channel zoq)
My conda env was setup by following the postBuild script in binder folder, before it was updated recently.

Any help would be appreciated.

2021-05-30 09:36 UTC, bkmgit commented
Can you try it in [binder](https://mybinder.org/), an example of using Binder is at https://github.com/jupyter-xeus/xeus-cling

2021-05-30 09:37 UTC, bkmgit commented
May also wish to open an issue at https://github.com/lava/matplotlib-cpp/

2021-05-30 11:07 UTC, bkmgit commented
Some other visualization choices are

- https://github.com/alandefreitas/matplotplusplus
- https://github.com/epezent/implot
- https://tkoyama010.github.io/pyvista-docs-dev-ja/
- http://docs.enthought.com/chaco/
- https://github.com/yhat/ggpy
- https://seaborn.pydata.org/
- https://pypi.org/project/ipyvtk-simple/
- https://plotly.com/python/ipython-notebook-tutorial/
- https://bokeh.org/

Python libraries can be called using https://github.com/lava/wrappy
Some of these are introduced at https://jupyterbook.org/interactive/interactive.html

2021-05-31 00:04 UTC, zoq commented
> ![Screenshot from 2021-05-30 08-40-11](https://user-images.githubusercontent.com/18904157/120090805-f053ba80-c122-11eb-9a67-7eab8be1a2c8.png)
> 
> Hi, any suggestions on how to fix this issue, every time I execute a cell containing some matplotlibcpp code, the xeus cling kernel dies.
> 
> My Local Env:
> OS: Manjaro 21.0.4
> Conda: 4.10.1
> Python: 3.7.10
> Xeus-cling: 0.9.0.13 (from channel zoq)
> My conda env was setup by following the postBuild script in binder folder, before it was updated recently.
> 
> Any help would be appreciated.

Can you check if https://lab.mlpack.org/v2/gh/mlpack/examples/master?urlpath=lab returns the same error, you can also use lab.mlpack.org and enter your fork and branch.

The cool thing about using binding and our repo is that everything is already configured.

2021-05-31 00:06 UTC, zoq commented
If you like to run the notebook locally, @jonpsy recently build a local notebook instance, maybe he can share his config?

2021-05-31 00:07 UTC, zoq commented
> > The dataset looks interesting, what about we finish the salary notebook, and then if @Davidportlouis agrees we do another one using the human-height dataset, there is no limit of notebooks we could implement, and the data exploration step for the human-height dataset would be interesting.
> 
> Sure @zoq, I would like to complete the salary prediction notebook, then implement human-height and also some other good datasets.

Sounds like a good plan to me.

2021-05-31 04:25 UTC, Davidportlouis commented
@zoq thanks for the suggestion to use lab.mlpack.org, the visualization works like a charm in the binder environment.
![Screenshot (225)](https://user-images.githubusercontent.com/18904157/120139274-bf908580-c1f5-11eb-8fff-65517559e2b0.png)

2021-05-31 17:49 UTC, jonpsy commented
> If you like to run the notebook locally, @jonpsy recently build a local notebook instance, maybe he can share his config?

I did, but it involves lot of ```#pragma``` calls on loading ```.so```files and gets kinda ugly. I think your suggestion of mlpack.lab is better, because it simulates the actual final product and loads up in decent amount of time. Looks like @Davidportlouis  has already has had success in this regard, good on him!

2021-06-01 00:47 UTC, zoq commented
> @zoq thanks for the suggestion to use lab.mlpack.org, the visualization works like a charm in the binder environment.

Happy to see that it worked out, the plot looks good.

2021-06-01 17:28 UTC, Davidportlouis commented
> > If you like to run the notebook locally, @jonpsy recently build a local notebook instance, maybe he can share his config?
> 
> I did, but it involves lot of `#pragma` calls on loading `.so`files and gets kinda ugly. I think your suggestion of mlpack.lab is better, because it simulates the actual final product and loads up in decent amount of time. Looks like @Davidportlouis has already has had success in this regard, good on him!

Thank you @jonpsy, I was also able to successfully reproduce mlpack.lab environment on my local machine. Now it works fine both on my local notebook as well as mlpack.lab

2021-06-06 16:46 UTC, zoq commented on salary_prediction_with_linear_regression/salary-prediction-linear-regression-cpp.ipynb
> +    "From the above metrics we can notice that our model MAE is ~5K, which is relatively small compared to our average salary of $76003, from this we can conclude our model is resonably good fit."
```suggestion
    "From the above metrics, we can notice that our model MAE is ~5K, which is relatively small compared to our average salary of $76003, from this we can conclude our model is a reasonably good fit."
```

2021-06-06 16:50 UTC, zoq reviewed
I think both notebooks are almost ready to be merged, just some minor style issues we should fix before.

2021-06-06 16:50 UTC, zoq commented on salary_prediction_with_linear_regression/salary-prediction-linear-regression-py.ipynb
> +    "From the above metrics we can notice that our model MAE is ~4K, which is relatively small compared to our average salary of $76003, from this we can conclude our model is resonably good fit."
```suggestion
    "From the above metrics, we can notice that our model MAE is ~4K, which is relatively small compared to our average salary of $76003, from this we can conclude our model is a reasonably good fit."
```

2021-06-06 17:01 UTC, rcurtin commented
I added the dataset to mlpack.org: http://mlpack.org/datasets/Salary_Data.csv.  Can you be sure to update `download_data_set.py` to include this dataset too? :+1:

2021-06-07 22:36 UTC, zoq commented on salary_prediction_with_linear_regression/salary-prediction-linear-regression-cpp.ipynb
> +    "data::Load(\"Salary_Data.csv\", inputs);"
To make it work, we have to download the dataset, in some of the other notebook I used `wget`, you can check:

https://github.com/mlpack/examples/blob/master/student_admission_regression_with_logistic_regression/student-admission-logistic-regression-cpp.ipynb

for an example.

2021-06-07 22:36 UTC, zoq commented on salary_prediction_with_linear_regression/salary-prediction-linear-regression-py.ipynb
> +    "data = pd.read_csv(\"Salary_Data.csv\")"
You can pass an url to pandas here to download the dataset, you can checkout:

https://github.com/mlpack/examples/blob/master/forest_covertype_prediction_with_random_forests/covertype-rf-py.ipynb

for an example.

2021-06-08 21:55 UTC, zoq reviewed
Besides the open style issue there is no other open issue from my side.

2021-06-08 21:55 UTC, zoq commented on salary_prediction_with_linear_regression/salary-prediction-linear-regression-cpp.ipynb
> +    "std::cout<<inputs.submat(0, 0, inputs.n_rows-1, 5).t()<<std::endl;"
Look like the patch above is still pending?

2021-06-09 02:18 UTC, zoq approved these changes
Awesome, no further comments from my side.

2021-06-10 13:25 UTC, zoq requested changes
Hm, looking at the build it looks like we are trying to extract a plain csv file.

2021-06-11 02:50 UTC, Davidportlouis commented
> Hm, looking at the build it looks like we are trying to extract a plain csv file.

I think there was some issue in downloading mnist dataset, now the build passes & mnist dataset is downloaded and extracted properly.

2021-06-11 17:08 UTC, zoq approved these changes

2021-06-12 17:04 UTC, merged

2021-06-12 17:04 UTC, zoq commented
Nice, thanks for the great notebooks.