Adapt examples to mlpack 4 transition
mlpack/examples pull request #206
Opened 2022-09-21 20:26 UTC by rcurtin

In this PR, I'll work to get all the examples building and passing the tests again.  Here I'll only work with the compiled C++ examples; I'll leave the notebooks for the next PR.

2022-10-01 16:25 UTC, rcurtin commented
Alright, this one is ready to go.  Next I'll adapt the notebook examples (but in a separate PR).

2022-10-01 16:43 UTC, shrit commented
is it good for review?

2022-10-01 17:10 UTC, rcurtin commented
Yep, ready for review :+1:

2022-10-02 16:06 UTC, shrit requested changes
Looks good in general, I have left a couple of comments

2022-10-02 16:06 UTC, shrit commented on mnist_cnn/mnist_cnn.cpp
> +#define MLPACK_ENABLE_ANN_SERIALIZATION
why do we need this define here?

2022-10-02 16:06 UTC, shrit commented on reinforcement_learning_gym/acrobot_dqn/acrobot_dqn.cpp
> -  module.Add<Linear<>>(64, DiscreteActionEnv::Action::size);
It is more readable when removing the inner brackets, I suppose this is because of the refactoring from boost visitors. It is much better now :+1:

2022-10-02 16:06 UTC, shrit commented on reinforcement_learning_gym/pendulum_dqn/pendulum_dqn.cpp
> -  network.Add<Linear<>>(DiscreteActionEnv::State::dimension, 128);
Is there any reason to remove the `DiscreteActionEnv` ?

2022-10-02 16:06 UTC, shrit commented on reinforcement_learning_gym/pendulum_sac/Makefile
> +LIBS_NAME := armadillo boost_iostreams
is there any reason why we are including the `boost_iostreams`?

2022-10-02 23:32 UTC, rcurtin commented on cifar10_cnn/Makefile
> +INCLFLAGS += -I/home/ryan/src/mlpack/build/deps/ensmallen-2.19.0/include/
Oh! This was accidentally checked in. Thank you for catching it. Fixed in d39e377.

2022-10-02 23:32 UTC, rcurtin commented on lstm_electricity_consumption/Makefile
> +INCLFLAGS += -I/home/ryan/src/mlpack/build/deps/ensmallen-2.19.0/include/
Also fixed in d39e377. :+1:

2022-10-02 23:32 UTC, rcurtin commented on lstm_stock_prediction/lstm_stock_prediction.cpp
> -#include <ensmallen.hpp>
Yeah, since ensmallen is a dependency of mlpack, it gets included automatically (the same is true of Armadillo).

2022-10-02 23:34 UTC, rcurtin commented on mnist_cnn/mnist_cnn.cpp
> +#define MLPACK_ENABLE_ANN_SERIALIZATION
Since this example serializes an ANN model, we need to make sure that we allow serialization of ANN layers; see also the bottom of [this section in the mlpack readme](https://github.com/mlpack/mlpack/#3-installing-and-using-mlpack-in-c). :+1:

2022-10-02 23:35 UTC, rcurtin commented on reinforcement_learning_gym/pendulum_sac/Makefile
> +LIBS_NAME := armadillo boost_iostreams
Yeah, the gym client uses iostreams, so we need to keep it. That's just a part of the local code for this example, so there is still no use of boost in mlpack.

2022-10-03 01:53 UTC, rcurtin commented on reinforcement_learning_gym/pendulum_dqn/pendulum_dqn.cpp
> -  network.Add<Linear<>>(DiscreteActionEnv::State::dimension, 128);
That parameter used to represent the input size, but now it is no longer needed because the network automatically determines the input size of each layer when training begins. :+1:

2022-10-04 22:18 UTC, merged